# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: aerobotX
email: info@aerobotx.net
description: > # this means to ignore newlines until "baseurl:"
  aerobotX ObliX is an unmanned airship designed from the ground up for safety,
  endurance, and maneuverability. Its unique combination of features make it
  particularly well-suited for safety-critical long-range missions.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://aerobotx.net" # the base hostname & protocol for your site
exclude:
  - Gemfile
  - Gemfile.lock
  - '*.iml'
  - README.md

kramdown:
  input: GFM
