# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: aerobotX Inc.
email: info@aerobotx.net
description: > # this means to ignore newlines until "baseurl:"
  AerobotX makes unmanned airship drones designed from the ground up for
  daylong missions, precise maneuverability, and safe operation over people.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://aerobotx.net" # the base hostname & protocol for your site
exclude:
  - Gemfile
  - Gemfile.lock
  - '*.iml'
  - README.md
opengraph:
  image: "https://aerobotx.net/assets/oblix.jpg"
  type: website

kramdown:
  input: GFM
